# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f7b958ad75cad33e3441ab5f42cb600949fef86ad3964c61fd5d9eb6f2ce70af8b669829a68f9a42056084afbb7543486a4f5605188c07c8ad8769e61781ccbb

test:
  secret_key_base: b3d9a557d9bbd087be5bda0cb5a0f3fa5931176b3e99502f0e1de2da63c163783ac57a50195776fc7e8b02e4cf64bf892bdbbb547b938168d35e456449e29ef9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
